---
# -- Values passed to the kube-prometheus-stack chart
kube-prometheus-stack:

  kubeControllerManager:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  prometheusOperator:
    manageCrds: false
    tls:
      enabled: false  # disable for now as I could not make it work
    tlsProxy:
      enabled: false  # disable for now as I could not make it work
    admissionWebhooks:
      enabled: false  # disable for now as I could not make it work

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

  grafana:
    sidecar:
      dashboards:
        searchNamespace: ALL
      datasources:
        searchNamespace: ALL
    plugins:
      - grafana-piechart-panel
